### ISSUE TITLE
Cisco ftd_configuration module not idempotent

### ISSUE THREAD

**Issue by justjais** [CiscoDevNet/FTDAnsible#79]
##### SUMMARY

Cisco ftd_configuration ansible module is not idempotent when tried with multiple references of the same object in array.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ftd_configuration

##### ANSIBLE VERSION

```paste below
2.7.5
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

mac os

##### STEPS TO REPRODUCE

```yaml
- hosts: ftd
  connection: httpapi
  tasks:
- name: Create URL Object
  ftd_configuration:
    operation: upsertURLObject
    data:
      name: GoogleURL
      description: URL for Google
      url: www.google.com
      type: urlobject
      register_as: url_obj

- name: Find Security Intelligence URL Policy
  ftd_configuration:
    operation: getSecurityIntelligenceURLPolicyList
    register_as: policies

- name: Setup SecurityIntelligenceURLPolicy
  ftd_configuration:
    operation: editSecurityIntelligenceURLPolicy
   data:
     id: "{{ policies[0]['id'] }}"
    name: "{{ policies[0]['name'] }}"
    version: "{{ policies[0]['version'] }}"
    whitelist:
    - "{{ policies[0]['whitelist'] + [url_obj] }}"
    type: securityintelligenceurlpolicy
    path_params:
      objId: "{{ policies[0]['id'] }}" 
```

##### EXPECTED RESULTS

Play should be idempotent in consecutive runs.

##### ACTUAL RESULTS

Play is not idempotent in consecutive runs and shows as `changed=True`, every times the play runs.

```paste below

```
